
version: '3.3'
networks:
  webapp:

services:
  nginx:
    image: nginx:latest
    build:
      context: ./nginx
    container_name: mynginx
    restart: always
    volumes:
      - ./nginx/mountfolder:/usr/share/nginx/html
      - ./nginx/webapp.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - pyweb
    #network_mode: host
    networks:
      - webapp

  pyweb:
    build:
      context: ./flaskcode
      dockerfile: Dockerfile
    container_name: mypyweb
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: webhook.py
    volumes:
      - ./flaskcode:/test
    #network_mode: host
    
    networks:
      webapp:
        aliases:
          - flask-app
          
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 "simplepage:myapp()"
    

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mymysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/usr/share/nginx/html
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3000:3306"
    environment:
      MYSQL_DATABASE: ${MYDB}
      MYSQL_ROOT_PASSWORD: ${MYPASS}
      TZ: Asia/Tokyo
    networks:
      - webapp
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

#  adminer:
#    image: adminer:latest
#    container_name: myadminer
#    restart: always
#    ports:
#      - "8000:8000"
#    networks:
#      - webapp
      
      